fix #24
hashicorp/packer-plugin-digitalocean pull request #44
Opened 2022-02-04 22:06 UTC by rizkybiz

This is a relatively small change. This updates the environment variable from `DIGITALOCEAN_API_TOKEN` to either `DIGITALOCEAN_TOKEN` or `DIGITALOCEAN_ACCESS_TOKEN`. These two environment variables are used in the Terraform plugin for Digital Ocean as well. As referenced in issue #24 , this makes any CI/CD pipelines that use both the Packer plugin and the Terraform plugin simpler from a variables standpoint.
I tested both ENV VARS with my DO account and token, both created images.

Closes #24

2022-02-08 10:07 UTC, azr requested changes
Hello ! Thanks for openning, I'm pretty sure the old values will be used by many users, what would be the best option you think ?

* deprecate now and release a `1.1` to make it a clear signal
* support them both, for now with a warning, then later on remove the old usage when we release `1.1` 
?

Thanks !

2022-02-08 14:04 UTC, rizkybiz commented
@azr If and when HCP Packer support comes to this plugin, I foresee a lot of folks wanting to upgrade to the latest to get those features. If they're still using `DIGITALOCEAN_API_TOKEN` and we don't explicitly call out that we've changed the supported ENV VARS, the UX would probably not be so good.
I'll go ahead and refactor to add back `DIGITALOCEAN_API_TOKEN` with a deprecation warning so we don't go breaking folks' workflows.

2022-02-09 01:25 UTC, rizkybiz commented
@azr I don't particularly love the flow I had to go through to bubble up a warning message from the config preparation into a place where I could access the Ui for output. Maybe I'm missing something in the SDK so feel free to make any suggestions. Thanks.

2022-02-09 12:56 UTC, azr commented on post-processor/digitalocean-import/post-processor.go
> -		p.config.APIToken = os.Getenv("DIGITALOCEAN_API_TOKEN")
Don't forget this one too !

2022-02-09 12:56 UTC, azr commented on builder/digitalocean/config.go
> +				"Please use either DIGITALOCEAN_TOKEN or DIGITALOCEAN_ACCESS_TOKEN moving forward.")
This is the right way !

2022-02-09 12:57 UTC, azr commented on builder/digitalocean/builder.go
> +	}
I think that you shouldn't need to do that, and that Packer core should display the warnings here. Was it not the case ?

2022-02-10 15:02 UTC, azr commented on builder/digitalocean/builder.go
> +		return nil, warnings, nil
Here, I think that we should probably always return everything without an if statement 🤔

2022-02-10 15:03 UTC, azr commented on builder/digitalocean/builder.go
> +		return nil, warnings, nil
Super nice catch !

2022-02-14 20:49 UTC, rizkybiz commented
@azr I took care of the post-processor breaking change as well now

2022-02-15 09:12 UTC, azr approved these changes
Nice one, LGTM ! Thanks !

2022-02-15 09:12 UTC, merged